/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BubbleMenu: typeof import('./src/components/Tiptap/BubbleMenu.vue')['default']
    CommandsList: typeof import('./src/components/Tiptap/CommandsList.vue')['default']
    Editor: typeof import('./src/components/Tiptap/Editor.vue')['default']
    PublishWidget: typeof import('./src/components/publish/PublishWidget.vue')['default']
  }
}
